Repository ROCm/rocWMMA, pull requests merged in 2022-12, with the labels that each got.

#105 Add script to dump benchmark outputs
  scripts/performance/BenchmarkGemm.sh
Labels: enhancement

#109 fixup
  library/include/rocwmma/internal/utils.hpp
Labels: noCI

#119 Fix hipRTC sample
  library/include/rocwmma/internal/utils.hpp
  samples/CMakeLists.txt
  samples/common.hpp
  samples/hipRTC_gemm.cpp
Labels: bug

#121 Doc updates
  README.md
  docs/source/Linux_Install_Guide.rst
  docs/source/Programmers_Guide.rst
  library/include/rocwmma/internal/config.hpp
  library/include/rocwmma/internal/cross_lane_ops.hpp
  library/include/rocwmma/internal/dpp.hpp
  library/include/rocwmma/internal/mfma_impl.hpp
  library/include/rocwmma/internal/wmma.hpp
  library/include/rocwmma/internal/wmma_impl.hpp
  library/include/rocwmma/rocwmma.hpp
  test/gemm/gemm_PGR0_LB0_MP0_MB_NC/device/kernel_device_func.hpp
  test/gemm/gemm_PGR0_LB0_MP0_SB_NC/device/kernel_device_func.hpp
  test/gemm/gemm_PGR1_LB2_MP0_MB_CP/device/kernel_device_func.hpp
  test/gemm/gemm_test_traits.hpp
  test/unit/unit_test_traits.hpp
Labels: documentation, noCI
