Repository ROCm/rocWMMA, pull requests merged in 2022-06, with the labels that each got.

#30 Fix resource alloc tracking
  test/dlrm/dlrm_resource.hpp
  test/dlrm/dlrm_resource_impl.hpp
  test/gemm/gemm_kernel_base.hpp
  test/gemm/gemm_kernel_base_impl.hpp
  test/gemm/gemm_resource.hpp
  test/gemm/gemm_resource_impl.hpp
  test/gemm/test/gemm_test.hpp
  test/hip_resource.hpp
  test/hip_resource_impl.hpp
  test/singleton.hpp
Labels: bug

#32 Data handling improvements.
  library/include/rocwmma/internal/broadcast.hpp
  library/include/rocwmma/internal/constants.hpp
  library/include/rocwmma/internal/coop_load.hpp
  library/include/rocwmma/internal/coop_store.hpp
  library/include/rocwmma/internal/io_traits.hpp
  library/include/rocwmma/internal/opaque_load.hpp
  library/include/rocwmma/internal/opaque_store.hpp
  library/include/rocwmma/internal/types.hpp
  library/include/rocwmma/rocwmma.hpp
  library/include/rocwmma/rocwmma_coop_impl.hpp
  library/include/rocwmma/rocwmma_impl.hpp
Labels: enhancement

#29 Refactor lds mapping
  library/include/rocwmma/internal/accessors.hpp
  library/include/rocwmma/internal/accessors_impl.hpp
  library/include/rocwmma/internal/coop_load.hpp
  library/include/rocwmma/internal/coop_store.hpp
  library/include/rocwmma/internal/io_config.hpp
  library/include/rocwmma/internal/io_shape.hpp
  library/include/rocwmma/internal/io_traits.hpp
  library/include/rocwmma/internal/layout.hpp
  library/include/rocwmma/internal/layout_impl.hpp
  library/include/rocwmma/internal/mapping_util.hpp
  library/include/rocwmma/internal/mapping_util_impl.hpp
  library/include/rocwmma/internal/opaque_load.hpp
  library/include/rocwmma/internal/opaque_store.hpp
  library/include/rocwmma/internal/types.hpp
  library/include/rocwmma/internal/utils.hpp
  library/include/rocwmma/rocwmma_coop_impl.hpp
  library/include/rocwmma/rocwmma_impl.hpp
  library/include/rocwmma/rocwmma_transforms.hpp
  library/include/rocwmma/rocwmma_transforms_impl.hpp
  test/gemm/device/mma_sync_multi_lds.hpp
  test/gemm/gemm_coop_schedule.hpp
  test/gemm/gemm_driver.hpp
  test/gemm/gemm_driver_impl.hpp
  test/gemm/gemm_global_mapping.hpp
  test/gemm/gemm_global_mapping_impl.hpp
  test/gemm/gemm_local_mapping.hpp
  test/gemm/gemm_local_mapping_impl.hpp
  test/gemm/lds_mapping_util.hpp
  test/gemm/test/common_test_params.hpp
  test/gemm/test/mma_sync_ad_hoc.cpp
  test/rocblas_reference.hpp
Labels: enhancement

#37 Reduce branching on cooperative load and store
  library/include/rocwmma/internal/coop_load.hpp
  library/include/rocwmma/internal/coop_store.hpp
  library/include/rocwmma/internal/types.hpp
  library/include/rocwmma/internal/types_impl.hpp
Labels: enhancement

#40 Workgroup aware tests
  library/include/rocwmma/internal/io_shape.hpp
  test/gemm/CMakeLists.txt
  test/gemm/detail/mma_sync_coop_wg.hpp
  test/gemm/device/mma_sync_multi_lds.hpp
  test/gemm/gemm_config.hpp
  test/gemm/gemm_global_mapping.hpp
  test/gemm/test/common_test_params.hpp
  test/gemm/test/mma_sync_coop_wg_test_16x16_nn_1x1.cpp
  test/gemm/test/mma_sync_coop_wg_test_16x16_nn_2x2.cpp
  test/gemm/test/mma_sync_coop_wg_test_16x16_nn_4x4.cpp
  test/gemm/test/mma_sync_coop_wg_test_16x16_nt_1x1.cpp
  test/gemm/test/mma_sync_coop_wg_test_16x16_nt_2x2.cpp
  test/gemm/test/mma_sync_coop_wg_test_16x16_nt_4x4.cpp
  test/gemm/test/mma_sync_coop_wg_test_16x16_tn_1x1.cpp
  test/gemm/test/mma_sync_coop_wg_test_16x16_tn_2x2.cpp
  test/gemm/test/mma_sync_coop_wg_test_16x16_tn_4x4.cpp
  test/gemm/test/mma_sync_coop_wg_test_16x16_tt_1x1.cpp
  test/gemm/test/mma_sync_coop_wg_test_16x16_tt_2x2.cpp
  test/gemm/test/mma_sync_coop_wg_test_16x16_tt_4x4.cpp
  test/gemm/test/mma_sync_coop_wg_test_32x32_nn_1x1.cpp
  test/gemm/test/mma_sync_coop_wg_test_32x32_nn_2x2.cpp
  test/gemm/test/mma_sync_coop_wg_test_32x32_nt_1x1.cpp
  test/gemm/test/mma_sync_coop_wg_test_32x32_nt_2x2.cpp
  test/gemm/test/mma_sync_coop_wg_test_32x32_tn_1x1.cpp
  test/gemm/test/mma_sync_coop_wg_test_32x32_tn_2x2.cpp
  test/gemm/test/mma_sync_coop_wg_test_32x32_tt_1x1.cpp
  test/gemm/test/mma_sync_coop_wg_test_32x32_tt_2x2.cpp
Labels: enhancement

#42 Fix AllColMajor indexing bug
  test/gemm/gemm_coop_schedule.hpp
Labels: bug

#43 Coop Load / Store performance enhancement on wg kernels
  library/include/rocwmma/internal/coop_load.hpp
  library/include/rocwmma/internal/coop_store.hpp
  library/include/rocwmma/rocwmma_coop_impl.hpp
  test/gemm/CMakeLists.txt
  test/gemm/gemm_coop_schedule.hpp
  test/gemm/gemm_driver_impl.hpp
  test/gemm/test/mma_sync_coop_wg_test_16x16_nn_8x8.cpp
  test/gemm/test/mma_sync_coop_wg_test_16x16_nt_8x8.cpp
  test/gemm/test/mma_sync_coop_wg_test_16x16_tn_8x8.cpp
  test/gemm/test/mma_sync_coop_wg_test_16x16_tt_8x8.cpp
  test/gemm/test/mma_sync_coop_wg_test_32x32_nn_4x4.cpp
  test/gemm/test/mma_sync_coop_wg_test_32x32_nt_4x4.cpp
  test/gemm/test/mma_sync_coop_wg_test_32x32_tn_4x4.cpp
  test/gemm/test/mma_sync_coop_wg_test_32x32_tt_4x4.cpp
Labels: enhancement

#44 Add GitHub actions file for docs build
  .github/workflows/docs.yaml
Labels: noCI
